author: vastwu
author_avatar: user_avatar.jpg
headerImage: header.jpg

paginate: 10
paginate_path: "/page:num"
excerpt_separator: "<!--more-->"
markdown: kramdown
markdown_ext: md
gems: [kramdown]
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
comments :
    provider : duoshuo
    duoshuo : 
      short_name : havee