highlighter: pygments
markdown: kramdown
markdown_ext: md
gems: [kramdown, pygments]
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true